title: p3ntest1ng
description: Artículos sobre ciberseguridad, hacking ético, resolución de CTFs, programación y mucho más.
author: WildZarek
avatar: /assets/images/about/avatar.png
email: 
url: wildzarek.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 5

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus: 

# Jekyll
# ======
exclude:
  - README.md
  - jekyll-theme-hamilton.gemspec
  
# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: WildZarek
  card: summary
logo: /assets/images/about/avatar.png
social:
  name: WildZarek
  links:
    - https://twitter.com/WildZarek
    - https://github.com/WildZarek
    - https://app.hackthebox.com/profile/18979
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es

location: Spain
skin: wildzarek

subscribe: false
